apiVersion: cert-manager.io/v1
 
kind: Certificate
metadata:
  name: stevanoz-xyz-tls
spec:
  secretName: stevanoz-xyz
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: stevanoz.xyz
  dnsNames:
    - stevanoz.xyz
    - www.stevanoz.xyz